# File used by Conda (if you use it) to install the necessary dependencies.

name: numerical-methods-env

channels:
  - defaults
  - conda-forge

dependencies:
  - python=>2.6
  - pip
  - pip:
    - numpy
