name: build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up git repository
        uses: actions/checkout@v2

      - name: Download Miniconda
        run: wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh

      - name: Install Miniconda
        run: bash -c "Miniconda3-latest-Linux-x86_64.sh -b"

      - name: Create the environment
        run: conda env create

      - name: Activate the environment
        run: conda activate numerical-methods-env

      - name: Run the project
        run: python3 main.py
