name: build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up git repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt -y install python3-numpy

      - name: Run the project
        run: python3 main.py
